name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf strapi-pm-2-vps/ && git clone https://github.com/StekolschikovV/strapi-pm-2-vps.git && cd strapi-pm-2-vps && npm i
        
            
#       - name: ls
#         run: ls
#       - name: e
#         run: echo 'The only winning move is not to play.' > demo.txt

#       - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
#         with:
#           ORIGIN: ${{ secrets.HOST }} # example.com || 8.8.8.8
#           SSHKEY: ${{ secrets.SSH }} # ----- BEGIN RSA PRIVATE KEY----- ...
#           NAME: production
#           PORT: ${{ secrets.PORT }} # 3000
#           USER: ${{ secrets.USER }} # admin
#       - run: ssh production ls --help
